CREATE TABLE T_Gamer (
    P_Gamer_ID()
    

    PRIMARY KEY (),
    CONSTRAINT $
    FOREIGN KEY () REFERENCES $ ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE T_Games (
    PRIMARY KEY (),
    CONSTRAINT $
    FOREIGN KEY () REFERENCES $ ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE T_Genre (
    PRIMARY KEY (),
    CONSTRAINT $
    FOREIGN KEY () REFERENCES $ ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE T_Account (
    PRIMARY KEY (),
    CONSTRAINT $
    FOREIGN KEY () REFERENCES $ ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE T_Hobbies (
    PRIMARY KEY (),
    CONSTRAINT $
    FOREIGN KEY () REFERENCES $ ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE T_Status (
    PRIMARY KEY (),
    CONSTRAINT $
    FOREIGN KEY () REFERENCES $ ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


/*
PRIMARY KEY (P_schueler_id),
CONSTRAINT F_Klassenlehrer
FOREIGN KEY (F_Klassenlehrer) REFERENCES T_Lehrer (P_Lehrer_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION
*/
